package rs

const (
	DATA_SHARDS     = 4
	PARITY_SHARDS   = 2
	ALL_SHARDS      = DATA_SHARDS + PARITY_SHARDS
	BLOCK_PER_SHARD = 16 * 1024 * 1024 // 16MB
	BLOCK_SIZE      = BLOCK_PER_SHARD * DATA_SHARDS
)
